print('hello world')
print('first change from the PC')
print('first change from Github')
print('second change from pc')
print('this change is done from pc using terminal cmd')
print('second change from git')
print('some random changes')